[package]
name = "siori"
version = "0.1.0"
edition = "2024"
[lib]
crate-type = ["cdylib"]
[dependencies.windows]
version = "0.58"
features = [
    "Data_Xml_Dom",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation"
]